apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  namespace: webapps # Namespace where the service account is created
  annotations:
    kubernetes.io/service-account.name: jenkins
